name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore
    - name: Package
      run: |
        cd src
        dotnet pack --no-restore --configuration Release PdfSharp
    - name: Push nuget to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        # Path of NuPkg
        nupkg-path: src/PdfSharp/bin/Release/*.nupkg
        # package repository owner
        repo-owner: lsparkes-etl
        # user account
        gh-user: lsparkes-etl
        # access token
        token: ${{ secrets.PACKAGE_TOKEN }}
